# Generated by Django 5.2.1 on 2026-06-13 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200)),
                ('performer_role', models.CharField(blank=True, max_length=50)),
                ('performer_branch_name', models.CharField(blank=True, max_length=100)),
                ('target_user_id', models.UUIDField(blank=True, null=True)),
                ('target_user_name', models.CharField(blank=True, max_length=150)),
                ('leave_date', models.DateField(blank=True, null=True)),
                ('leave_type', models.CharField(blank=True, max_length=50)),
                ('old_slot_id', models.UUIDField(blank=True, null=True)),
                ('new_slot_id', models.UUIDField(blank=True, null=True)),
                ('meta_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
