# Generated by Django 5.2.1 on 2026-06-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target_branch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]