# Generated by Django 5.2.1 on 2026-06-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
