/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppTeacherIndexRouteImport } from './routes/_app/teacher/index'
import { Route as AppParentIndexRouteImport } from './routes/_app/parent/index'
import { Route as AppManagerIndexRouteImport } from './routes/_app/manager/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppTeacherLeavesRouteImport } from './routes/_app/teacher/leaves'
import { Route as AppParentRescheduleRouteImport } from './routes/_app/parent/reschedule'
import { Route as AppManagerReschedulesRouteImport } from './routes/_app/manager/reschedules'
import { Route as AppManagerLeavesRouteImport } from './routes/_app/manager/leaves'
import { Route as AppAdminRolesRouteImport } from './routes/_app/admin/roles'
import { Route as AppAdminBranchesRouteImport } from './routes/_app/admin/branches'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppAdminApprovalsRouteImport } from './routes/_app/admin/approvals'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherIndexRoute = AppTeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => AppRoute,
} as any)
const AppParentIndexRoute = AppParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerIndexRoute = AppManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherLeavesRoute = AppTeacherLeavesRouteImport.update({
  id: '/teacher/leaves',
  path: '/teacher/leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppParentRescheduleRoute = AppParentRescheduleRouteImport.update({
  id: '/parent/reschedule',
  path: '/parent/reschedule',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerReschedulesRoute = AppManagerReschedulesRouteImport.update({
  id: '/manager/reschedules',
  path: '/manager/reschedules',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerLeavesRoute = AppManagerLeavesRouteImport.update({
  id: '/manager/leaves',
  path: '/manager/leaves',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRolesRoute = AppAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBranchesRoute = AppAdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApprovalsRoute = AppAdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/branches': typeof AppAdminBranchesRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/manager/leaves': typeof AppManagerLeavesRoute
  '/manager/reschedules': typeof AppManagerReschedulesRoute
  '/parent/reschedule': typeof AppParentRescheduleRoute
  '/teacher/leaves': typeof AppTeacherLeavesRoute
  '/admin/': typeof AppAdminIndexRoute
  '/manager/': typeof AppManagerIndexRoute
  '/parent/': typeof AppParentIndexRoute
  '/teacher/': typeof AppTeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/branches': typeof AppAdminBranchesRoute
  '/admin/roles': typeof AppAdminRolesRoute
  '/manager/leaves': typeof AppManagerLeavesRoute
  '/manager/reschedules': typeof AppManagerReschedulesRoute
  '/parent/reschedule': typeof AppParentRescheduleRoute
  '/teacher/leaves': typeof AppTeacherLeavesRoute
  '/admin': typeof AppAdminIndexRoute
  '/manager': typeof AppManagerIndexRoute
  '/parent': typeof AppParentIndexRoute
  '/teacher': typeof AppTeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/admin/approvals': typeof AppAdminApprovalsRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/branches': typeof AppAdminBranchesRoute
  '/_app/admin/roles': typeof AppAdminRolesRoute
  '/_app/manager/leaves': typeof AppManagerLeavesRoute
  '/_app/manager/reschedules': typeof AppManagerReschedulesRoute
  '/_app/parent/reschedule': typeof AppParentRescheduleRoute
  '/_app/teacher/leaves': typeof AppTeacherLeavesRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/manager/': typeof AppManagerIndexRoute
  '/_app/parent/': typeof AppParentIndexRoute
  '/_app/teacher/': typeof AppTeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notifications'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/roles'
    | '/manager/leaves'
    | '/manager/reschedules'
    | '/parent/reschedule'
    | '/teacher/leaves'
    | '/admin/'
    | '/manager/'
    | '/parent/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notifications'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/branches'
    | '/admin/roles'
    | '/manager/leaves'
    | '/manager/reschedules'
    | '/parent/reschedule'
    | '/teacher/leaves'
    | '/admin'
    | '/manager'
    | '/parent'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/notifications'
    | '/_app/admin/approvals'
    | '/_app/admin/audit'
    | '/_app/admin/branches'
    | '/_app/admin/roles'
    | '/_app/manager/leaves'
    | '/_app/manager/reschedules'
    | '/_app/parent/reschedule'
    | '/_app/teacher/leaves'
    | '/_app/admin/'
    | '/_app/manager/'
    | '/_app/parent/'
    | '/_app/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher/': {
      id: '/_app/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AppTeacherIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/': {
      id: '/_app/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof AppParentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/': {
      id: '/_app/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof AppManagerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher/leaves': {
      id: '/_app/teacher/leaves'
      path: '/teacher/leaves'
      fullPath: '/teacher/leaves'
      preLoaderRoute: typeof AppTeacherLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent/reschedule': {
      id: '/_app/parent/reschedule'
      path: '/parent/reschedule'
      fullPath: '/parent/reschedule'
      preLoaderRoute: typeof AppParentRescheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/reschedules': {
      id: '/_app/manager/reschedules'
      path: '/manager/reschedules'
      fullPath: '/manager/reschedules'
      preLoaderRoute: typeof AppManagerReschedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/leaves': {
      id: '/_app/manager/leaves'
      path: '/manager/leaves'
      fullPath: '/manager/leaves'
      preLoaderRoute: typeof AppManagerLeavesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/roles': {
      id: '/_app/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AppAdminRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/branches': {
      id: '/_app/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AppAdminBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/approvals': {
      id: '/_app/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AppAdminApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppAdminApprovalsRoute: typeof AppAdminApprovalsRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBranchesRoute: typeof AppAdminBranchesRoute
  AppAdminRolesRoute: typeof AppAdminRolesRoute
  AppManagerLeavesRoute: typeof AppManagerLeavesRoute
  AppManagerReschedulesRoute: typeof AppManagerReschedulesRoute
  AppParentRescheduleRoute: typeof AppParentRescheduleRoute
  AppTeacherLeavesRoute: typeof AppTeacherLeavesRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppManagerIndexRoute: typeof AppManagerIndexRoute
  AppParentIndexRoute: typeof AppParentIndexRoute
  AppTeacherIndexRoute: typeof AppTeacherIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppAdminApprovalsRoute: AppAdminApprovalsRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBranchesRoute: AppAdminBranchesRoute,
  AppAdminRolesRoute: AppAdminRolesRoute,
  AppManagerLeavesRoute: AppManagerLeavesRoute,
  AppManagerReschedulesRoute: AppManagerReschedulesRoute,
  AppParentRescheduleRoute: AppParentRescheduleRoute,
  AppTeacherLeavesRoute: AppTeacherLeavesRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppManagerIndexRoute: AppManagerIndexRoute,
  AppParentIndexRoute: AppParentIndexRoute,
  AppTeacherIndexRoute: AppTeacherIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
